//States de productos
export const OBTNER_PRODUCTOS_EXITO = 'OBTNER_PRODUCTOS_EXITO';

//State para el pedido
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
export const CONFIRMAR_ORDENAR_PLATILLO = 'CONFIRMAR_ORDENAR_PLATILLO';
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const PEDIDO_ORDENADO = 'PEDIDO_ORDENADO';